### ISSUE TITLE
用言の変換

### ISSUE THREAD

**Issue by h-youhei** [esrille/ibus-replace-with-kanji#26]
梅棹式ではなく、単に難しい漢字を使わないという方式だと、結構な頻度で用言を変換します。
用言変換キーを単独でもうけて、用言の変換が1動作でできる方がうれしいです。

**Comment by ShikiOkasaka** [comment]
コメントありがとうございます。

和語に漢字をなるべくもちいぬようにする、というのは梅棹忠夫さんだけでなく、高島俊男さん、新村出さんらも、のべられている一方で、どこまで漢字を許容するか、というのは、個人差がたしかにみられます。

梅棹式よりはおおめに漢字をつかいたいのであれば、「1音の動詞の漢字」の漢直入力操作をやめて、〔\〕キーは用言置換用のキーということにして、

    き〔\〕 →  決，効，消，切，着，聞，利

と変換する、といった方式がありそうです。梅棹式であればいずれにしても例外的な機能ですが、これで常用するとなると、下記のような課題があるでしょうか。

* 変換効率を優先するのなら、多少おくりがなをまぜて変換したほうが有利な点(きえ→消え、など)。
* よみの指定が現代かなづかいの「送り仮名の付け方」によっている点(1音の場合は問題ないけれども)。
* 現行の常用漢字の訓よみのままでは、漢字がおおすぎる点。

単純に訓よみがあれば漢字ということであれば現行のIMEでもよいわけので、ibus-replace-with-kanjiでどんなふうに処理するか、というのは、梅棹忠夫さんの、

> ごく少数の漢字をまじえてもよいのではないか、というかんがえかたもでてくるであろうが、これはかなり慎重なあつかいを必要とする。

[1]というラインはかえずに、実験をしていきたいとおもっています。「消え」の例だと、

    き〔\〕え → 消え
    き〔\〕か → 聞か，効か
    
のように候補がしぼられていくるような方法もかんがえられそうです。

最近では、平安時代から訓よみがもう定着していた動詞の漢字は、常用漢字293字中の182字といったこともしらべられています[2]。名詞の山(やま)・水(みず)のように、動詞でも漢字がなじむように感じられる字がある理由をこうしたところにみつけられことは、もしかしたらあるようにもおもっています。

[1] 『[日本語と事務革命](https://www.amazon.co.jp/dp/4062923386)』，梅棹忠夫，講談社学術文庫，2015.
[2] 『[漢字とその訓読みとの対応の歴史的変遷](https://www.ninjal.ac.jp/event/specialists/project-meeting/files/JCLWorkshop_no8_papers/JCLWorkshop_No.8_18.pdf)』, 芮真慧, 2015.

**Comment by h-youhei** [comment]
- 必要な操作を少なくする
- 変換効率のために送りがなを少し混ぜる

という観点から考えると、送りがな位置指定キー(ここでは \ とします)の次に文字が入力されると変換が開始されるという方法が良いように感じました。

例えば、`き[\]`と入力されている状態で`え`と入力した時点で`消え`と変換されるということです。

以下、余談です。
僕は分からない言葉を漢字から連想するときに、その漢字を訓読み(たいてい送りがなを伴う)することが多いです。和語をすべてひらがなで書くことにすると、漢字が分かっていてあえてひらがなで書いている間は問題ありませんが、数世代後に和語と漢字がつながらなくなったときに問題になるのではないかなと思っています。

**Comment by h-youhei** [comment]
メモ
- かな入力とローマ字入力に対応するために、かなとローマ字子音を相互変換する
- 辞書側では、送りがなとして、かなとローマ字子音どちらを持つか

**Comment by h-youhei** [comment]
- 活用のことを考えると、行(を表すローマ字)を辞書側で持つのが良さそう。ア行はどうするか。
- ヤ行、ワ行五段活用動詞はどうするか。ヤ行五段活用動詞はそもそもあるのか。
- 活用がない語、「しい」系形容詞、「か」系形容詞はとくに問題ない。
- カ行変格活用動詞、「しい」でない形容詞は送りがなで絞らなくてもよいのではないか。

**Comment by h-youhei** [comment]
ア行五段活用の語は、なさそう。

促音便(っ) タ、ラ、ワ行
例︰取る 取って

はつ音便(ん) ナ、バ、マ行
例︰飛ぶ 飛んで

イ音便、ウ音便 
音便について[参考サイト](http://kyujin.nihongokyouiku.net/entry/2017/01/20/154026)

上一段活用、下一段活用の未然形、連用形は活用部分がなくなる。

**Comment by ShikiOkasaka** [comment]
課題の整理、ありがとうございます。

辞書でのもちかたは、
き-る /着/ # 上下1段活用系
き-r /切/  # 5段活用
くらいで、簡易的には、あとはプログラムでだいたい処理できます。

語幹のはなしは、すこしまえにツイートしたことがありました:
https://twitter.com/shiki_okasaka/status/858171055810138112

**Comment by ShikiOkasaka** [comment]
ただくわえて、語幹のかんがえかたと、おくりがなの関係は面倒なところがあって、高島俊男さんの『漢字と日本語』のあとがきなどは、おもしろいかな、とおもいます。
https://www.amazon.co.jp/dp/4062883678

**Comment by ShikiOkasaka** [comment]
## おくりがなについて

※ おくりがなに関することを、簡単にまとめておきます。

「始」を例にすると、訓は、「はじめる」と「はじまる」が常用漢字表にあげられている。

語幹は、現代的には、
はじめ- (母音語幹動詞)
はじまr- (子音語幹動詞)
とするよう。

共通部分の「はじ」をとって、「め」や「ま」からおくる、と解釈すれば、｢送り仮名の付け方｣にそったかたちになる。

学校文法だと、
はじ-める (下１段)
はじま-る (５段)
とならう。

※ 学校文法では、母音語幹動詞の語幹の最後の１字も活用語尾とするので、「見る」には語幹がない、というような説明になる。

これは、「始(はじ)める」と「始(はじま)る」は活用語尾をおくるだけで区別できる、という高島さんのこのみにつながる。

｢送り仮名の付け方｣では、「許容」として、「読み間違えるおそれのない場合は（略）省くことができる」というのがあって、高島さんが絶対にいやという、

落とす〔落す〕

があげられている（どちらも可）。なので「始(はじま)る」も実際には許容されるはず。

ほかにも、「浮」は、

うk-
うかれ-
うかb-
うかべ-

で(-ない、とつなげるとちがいがわかりやすい)、共通部分の「う」をとって、「く」や「か」からおくる、と解釈すれば、｢送り仮名の付け方｣にそったかたちになる。ただこれも、「許容」で、

浮かぶ〔浮ぶ〕

があげられている。

このあたりの事情も、保科さんの『国語問題５０年』の「むすび」がくわしくて、おくりがなは「よむ力の高い人」ほどすくなくしたいもの、ということがかかれいる。送りがな法というのは、「いかに苦心してみたところで、一貫した法則で組み立てることができない」とも。

高島さんは「落とす」とかくくらいなら、かなで「おとす」とかく、ということをかかれている。ラジカルにつきすすめていくと、梅棹さんのように、用言はかなでかく、ということになるのだろう。

## 辞書のもちかた

といったことをふまえると、辞書のもちかたとしては、｢送り仮名の付け方｣にそったかたちに限定してよければ、

うk- /浮/
はじm- /始/

のように簡略化してもつ、というのがひとつのかんがえかた(高島さんはこうとらえて「始まる」で妥協された)。

逆に、「落す」のように「許容」されている表記はつかいたい、とすれば、

うk- /浮/
うかれ- /浮かれ/浮れ/
うかb- /浮か/浮/
うかべ- /浮かべ/浮べ/

のようにもつ、というのもひとつかと(キー入力は、

うか\れ → 浮れ

とできるとよいだろう)。

## 課題

いずれにしても、こういった辞書をどう用意するか、という点は課題としてのこる(手作業はなるべくさけたい)。

**Comment by ShikiOkasaka** [comment]
naist-jdicと対照して、活用形と許容よみ(;9)を付加した常用漢字表をプログラムでつくることができました。

https://gist.github.com/ShikiOkasaka/41fed6168b770314f587326848fdb2f9

「落す」はnaist-jdicにふくまれていて、「おと―s;9」というかたちにできています。

    落,ラク;3,お―ち;3,お―とs;3,おと―s;9

「浮」も、「浮れ」以外はあったようです。

    浮,フ;7,う―k;7,う―かれ;7,う―かb;7,うか―b;9,う―かべ;7,うか―べ;9

「始(はじま)る」はnaist-jdicにふくまれていないようで展開できていません。活用形はしらべられているので、強制的に追加してもよいかもしれませんが、なにか基準は必要そうです。逆に「出始る」 (読み デハジメル)がありました。なかなかむずかしいものがあります。

    始,シ;3,はじ―め;3,はじ―まr;3

ただひとまず辞書のほうは目途がたったので、変換処理のほうもつめていくと、実装まですすめられそうです。

**Comment by h-youhei** [comment]
「音読み」と「する(とその派生)」を合わせた語
例︰愛する、信じる
が現在の送りがな辞書に含まれていません。
和語ではないですが、これらの語は用言の変換として扱うのが直感的ではないかと思います。
実際これらの語をこの入力エンジンで、はじめて入力するとき「\」をからめて入力しようとしました。

**Comment by ShikiOkasaka** [comment]
技術的にみると、常用漢字表のなかでサ変の動詞は「欲(ほっ)する」だけです。ですので基本としては、ibus-replace-with-kanji では、サ変は語幹を置換してから「する」とうつ(「欲する」だけが例外)、とおぼえられるのがよいかとおもいます。

ただ「信じる」のようにサ変から上一段化しているものは、感覚としては和語のようにつかわれていることは想像できます。このあたりは日本語の変化もはやいようで(※)、常用漢字表以外の資料でまとまったものがあれば、とりいれてもよいのかもしれません。
(※) http://ci.nii.ac.jp/naid/110008799628

**Comment by ShikiOkasaka** [comment]
かんたんに田野村 忠温さんの下のふたつの資料をみてみました。

[1] サ変動詞の活用のゆれについて--電子資料に基づく分析 (特集:電子化資料による日本語研究), 2001
http://ci.nii.ac.jp/naid/40005174758

[2] サ変動詞の活用のゆれについて(続)大規模な電子資料の利用による分析の精密化, 2009
http://ci.nii.ac.jp/naid/40016557492

[2] は一部の漢字で、1940年代から2000年代にかけて、サ変の五段化(適は10%未満から90%弱に)、あるいはサ変の上一段化(感は10%未満から80%超に)が急速に、あるいは加速的にすすんでいることをしめしていて、おもしろいものでした。

1981年の常用漢字の制定時でも上一段化はまだそれほどすすんでいなかったようです。そういう意味でも、常用漢字表の音訓表をみて違和感をもたれたのは、おもしろい現象だとおもいました。

梅棹さんなら、サ変でなくなった字は、いずれかながきにされそうにもおもいますが、梅棹式によらないかたがこれらに漢字をつかっていても、和語を漢字でかかれるよりはよいのかもしれませんね。

**Comment by ShikiOkasaka** [comment]
田野村忠温さんの論文であげられている漢字を整理すると、以下のような感じになる。

## 「属する」類(五段化がすすんでいる):

### I類(1拍語。五段化が完了している。):
科課期帰窮御死資持辞
謝処叙堕比付模利和

### IIa類(2拍語で特殊拍をふくまない。五段化の途中。):
愛臆介解害画解激熟食
即属対題託適毒廃排復
服目訳浴略類

### IIb類(2拍語で特殊拍をふくむ。五段化はおくれている。):
(長音) 供制遇抗称証賞奏徴呈表評有要擁労
(撥音) 冠関存反貧偏滅面
(促音) 圧逸喫屈決察失接絶達脱徹熱発罰律

## 「信ずる」類(上一段化がすすんでいる):

案映詠演応感興禁吟献
減講高参散准殉準乗信
生煎損存嘆断談長通転
点投動同難任認念判封
変弁報奉崩命銘免論

※ これらはコーパス上でそう、というだけなので、IMEの辞書にどれをいれるかは、日常感(≒かながきにしても違和感がない、和語のようにひろく認識されている)などまた別の基準がほしい(意見がわかれるようなものは、個人辞書でもってもよい)。

**Comment by ShikiOkasaka** [comment]
e457cf496e8e7aa4d3b7f23175dfdd992523003c で基本部分を実装しました。

    お―とす[変換]

で、「落とす」に変換できるようになっています。―は、漢字の部分のおわりを指示するもので、\キーで入力します。

いままでのように、

    あ―[変換]

では１８個も候補がでてくるよみも、

    あ―る[変換]

だと、「有る」と「在る」の２候補にしぼられた状態でスタートできます。

また、辞書を restrained.9.dic に設定すると、いわゆる許容されているおくりがなも、つかえるようになります。たとえば、

    おと―す[変換]

で、「落す」に変換できます。

※ ―のあとに、かなを入力した時点で自動で変換を開始する方式の実験もこれからすすめていく予定です。

※ 従来の漢直方式はつかえなくなっています。梅棹式表記では、いずれにしても漢直方式は使用頻度がかなりひくいものでしたので、変換方式だけになっても、影響はそれほどおおきくないかもしれません。

**Comment by ShikiOkasaka** [comment]
※ カ行変格活用は、まだ辞書でもっていません。

**Comment by ShikiOkasaka** [comment]
ca42efb05f042b220924941e81bfeb5689fd4911 で左シフトキーのからおしで―を入力できるようにしてみています(評価中)。

**Comment by ShikiOkasaka** [comment]
カ行変格活用に対応: 91d7843a1aafab3827cb3bc85184d7ba32959ab0

**Comment by ShikiOkasaka** [comment]
「属する」類、「信ずる」類については、別Issueで検討することとして、このIssueはクローズします。
