### ISSUE TITLE
Arch Linuxにて動作しない

### ISSUE THREAD

**Issue by h-youhei** [esrille/ibus-replace-with-kanji#27]
関係ありそうなソフトウェアのバージョン
ibus 1.5.16
python 3.6.1

やったこと
git clone
cd
autogen
make
sudo make install
ibus setupからこのimeを追加
xinitrcをibus用に書き換え
ログアウト
ログイン

インプットメソッド切替に割り当てたキーを押すと、トレイアイコンが1秒ほど「あ」になり、もとに戻ります。
アルファベットが直接入力されます。

**Comment by h-youhei** [comment]
ごめんなさい、動作していました。
インプットメソッドの切替でこのメソッドが英数モードで起動する。
ここで動作していないと勘違いしました。
caps lockキーでかなモードに変更する必要がありました。

直接入力用のレイアウトを外す旨をドキュメントに書いておくと混乱が防げそうです。

**Comment by ShikiOkasaka** [comment]
動作報告ありがとうごさいます。
IBusも入力モードをトップバーに表示できるようにもどって(?)いるので、一時の混乱も解消されそうな印象もありますがどうでしょうか。

このイシューはひとまずクローズしておきます。
