### ISSUE TITLE
usキーボードでのスペースの入力

### ISSUE THREAD

**Issue by h-youhei** [esrille/ibus-replace-with-kanji#32]
スペースを入力するためには、shiftキーを押しながらスペースキーを押すことをドキュメントに書いたほうがいいと思います。

スペースキーを変換キーと共用することができれば、必要動作が減って好ましいです。
問題はスペースと変換のどちらとして扱えばいいかの判定方法です。
なにかよい方法はあるでしょうか？僕は思いつきません。

**Comment by ShikiOkasaka** [comment]
USキーボードのローマ字入力で想定している空白の入力方法は [']キーです。
レイアウト図はまとめておいたほうがよいですね。

※ [shift]-[space]は、たまたま今のところそれでも入力できてしまう、といったところです。指１本でも入力できるように、というのはアクセシビリティーの原則としてかんがえています。

**Comment by ShikiOkasaka** [comment]
参考: 配列図と簡単な説明を次のページでみられるようにしました。
https://esrille.github.io/ibus-replace-with-kanji/layouts.html
