### ISSUE TITLE
レイアウトが変更できない

### ISSUE THREAD

**Issue by h-youhei** [esrille/ibus-replace-with-kanji#33]
症状
レイアウトを変更してもローマ字入力のまま変わらない

os
arch linux

使用ツール
dconf-editor

`/desktop/engine/replace-with-kanji-python/layout`の値を以下にするのを試しました。
- ~/.config/ibus-replace-with-kanji/kana.json
- $XDG_CONFIG_HOME/ibus-replace-with-kanji/kana.json
- /home/ユーザ名/.config/ibus-replace-with-kanji/kana.json
- /usr/local/share/ibus-replace-with-kanji/layouts/レイアウト名(jis.109.jsonとnew_stickney.json)

関係あるかもしれないこと
- gnomeを利用していない
- `ibus-setup`の`preferences`ボタンがグレーアウトしている
- 途中で`use default value`をonにして再度offにした
- kana.jsonは既存のレイアウトをコピーして大幅に書きかえてあるのでどこかでミスがあるかもしれない

**Comment by ShikiOkasaka** [comment]
必要であれば、logging-levelをDEBUGにあげて、

    tail -f ~/.local/share/ibus-replace-with-kanji/ibus-replace-with-kanji.log

で何かエラーがでていないか、みてみてください。

**Comment by h-youhei** [comment]
ありがとうございます。

`ERROR:engine:file レイアウト名 not found`と出ています。

`use default value`をonにした場合も /usr/local/share/ibus-replace-with-kanji/layouts/roomazi.json に対して同様のエラーが出ています。

/usr/local/share/ibus-replace-with-kanji/layouts/レイアウトファイル にshellからはアクセスできます。

**Comment by ShikiOkasaka** [comment]
ファイルモードを確認できるでしょうか? Fedoraでは、
```
$ ls -l /usr/local/share/ibus-replace-with-kanji/layouts/
total 52
-rw-r--r--. 1 root root 3694 Jun 16 15:02 jis.109.json
-rw-r--r--. 1 root root 3729 Jun 16 15:02 new_stickney.json
-rw-r--r--. 1 root root 3762 Jun 16 15:02 new_stickney.nisse.json
-rw-r--r--. 1 root root 5764 Jun 16 15:02 nicola_f.json
-rw-r--r--. 1 root root 5763 Jun 16 15:02 nicola.json
-rw-r--r--. 1 root root 5617 Jun 16 15:02 roomazi.109.json
-rw-r--r--. 1 root root 5573 Jun 16 15:02 roomazi.json
-rw-r--r--. 1 root root 5638 Jun 16 15:02 tron.json
```
といったようになります。

いまのところ、こちらでテストをしている環境は、
* Fedora 25
* Ubuntu 16.04 LTS
* Raspbian Jessie (対応は、あたらしいStreachのリリースまち)

になります。archについてはテストをしていないので、そのあたりで、お気づきの点もあれば、おしらせください。

**Comment by ShikiOkasaka** [comment]
ddeb031397069e3dda88a43a3e4ca96e714f5cb1 で、OSError例外についてもひろうようにしました。ファイルモードの問題であれば、
```
ERROR:engine:Error: [Errno 13] Permission denied: '/usr/local/share/ibus-replace-with-kanji/layouts/nicola.json'
```
といったぐあいに、より詳細に原因がわかります。あわせて利用してください。

**Comment by h-youhei** [comment]
```
total 52
-rw-r--r-- 1 root root 3694 Jun 17 19:26 jis.109.json
-rw-r--r-- 1 root root 3729 Jun 17 19:26 new_stickney.json
-rw-r--r-- 1 root root 3762 Jun 17 19:26 new_stickney.nisse.json
-rw-r--r-- 1 root root 5764 Jun 17 19:26 nicola_f.json
-rw-r--r-- 1 root root 5763 Jun 17 19:26 nicola.json
-rw-r--r-- 1 root root 5617 Jun 17 19:26 roomazi.109.json
-rw-r--r-- 1 root root 5573 Jun 17 19:26 roomazi.json
-rw-r--r-- 1 root root 5638 Jun 17 19:26 tron.json
```

linux 4.11.5-1
xorg-server 1.19.3-2
xmonad 0.13-1
ibus 1.5.16-1
python 3.6.1-1
systemd 232-8
dconf 0.26.0+1+g701d19d-1
dconf-editor 3.23.4+48+g9acdf0a-1
gtk2 2.24.31-1
gtk3 3.22.15-1

**Comment by h-youhei** [comment]
更新後`Error:engine:Unexpected error: レイアウト名`にエラー内容が変わりました。

**Comment by ShikiOkasaka** [comment]
ファイルモードの問題ではなかったですね。

Unexpected error の内容もログにだすように、
ab5620f60214b9720ef4cde3b1086f61250330ca
で変更しました。こちらの出力結果もみれますでしょうか?

**Comment by h-youhei** [comment]
```echo $IBUS_REPLACE_WITH_KANJI_LOCATION```
なにも表示されない

これは関係ありませんか？

**Comment by h-youhei** [comment]
<class 'TypeError'> loads() takes 1 positional argumet but 2 were given

**Comment by ShikiOkasaka** [comment]
そこでしたか!

※ $IBUS_REPLACE_WITH_KANJI_LOCATIONは、ibus-engine-replace-with-kanji スクリプト内で設定しています:
https://github.com/esrille/ibus-replace-with-kanji/blob/master/engine/ibus-engine-replace-with-kanji.in
コマンドシェルではみれなくて、問題ありません。

**Comment by ShikiOkasaka** [comment]
Python 3.6ではうごかないコードになっていたようです。
a8f2e1521f56c9486669f3f521d23f59645def8f
のように修正しました。
レイアウトを変更できるようになっているでしょうか?

**Comment by h-youhei** [comment]
変更できるようになりました。
ありがとうございました。

頭の~をホームディレクトリとして展開されると便利だと思います。

**Comment by ShikiOkasaka** [comment]
ご報告ありがとうございました。
Fedoraも26からPython 3.6がはいってくるようですので、ほかにも問題がないか確認しておきます。

~の件は、別Issueで登録してくだいますでしょうか?
設定は、このままずっとdconf-editor推奨でよいのか、専用GUIはなくてもよいか、ということはあるのですけれども。
