### ISSUE TITLE
頭の~をホームディレクトリに置換する

### ISSUE THREAD

**Issue by h-youhei** [esrille/ibus-replace-with-kanji#35]
ユーザーがパスを入力するところでは、頭の~をホームディレクトリに置換すると便利だと思います。

**Comment by ShikiOkasaka** [comment]
補足: 将来的にUIをどうするか、ということもあるので、いまのところ優先度はたかくありません。

**Comment by ShikiOkasaka** [comment]
特に必要性がないようなので、いったんクローズします。
