### ISSUE TITLE
外部プログラムからの入力モード操作との相性

### ISSUE THREAD

**Issue by h-youhei** [esrille/ibus-replace-with-kanji#36]
###  要望
- ひらがな入力モードで起動する
- Capslockでの入力モードの切り替えを無効にする

これらの設定項目を設けてほしいです。

### 背景
- `ibus engine`で現在の状態を取得
- `ibus engine xkb:us::eng`でimeを無効化(us101系レイアウトの場合)
- `ibus engine replace-with-kanji-python`でimeを有効化

を利用して外部プログラムからibusを操作できます。

vimでノーマルモードにしたときにimeを無効化し、インサートモードにしたときにもとの状態を復元するのが僕の用途です。

このような使い方をする場合、
- ibusに直接入力用のレイアウト(xkb:us ::eng等)と変換エンジン(replace-with-kanji-python)を登録する
- ibus起動時の入力エンジンに直接入力用のレイアウトを指定する
- 変換エンジンが日本語モードで起動するようにする
- モードの切り替え方法をibusのレイアウト切り替えに統一する

こうするとうまく扱えます。

### 他の方法
pythonのモジュールシステムをよく理解していないので自信がありませんが、
- 現在の入力モードを取得する
- 入力モードを切り替える

これらの機能をAPIとして公開して、外部プログラムから変換エンジンを直接操作するという手も考えられます。

この方法にすると、変換候補を文脈で並びかえる機能を加えた場合に、周辺テキストAPIに対応していないアプリケーションでも数字や英字に続く語(例:1回)の並びかえができるのではないかと思います。

**Comment by ShikiOkasaka** [comment]
APIを用意する、という方向だと、
% gsettings get org.freedesktop.ibus.engine.replace-with-kanji-python mode あ
のような方法が、一番実装上は単純な気もしますが、どうでしょうか?

ibusのエンジンごときりかえる方法は不評だった印象もあり、理想の方法としては、といったことがもしあれば、あわせておしえてください。

**Comment by h-youhei** [comment]
### ただし書き
ibusのエンジンを切りかえる方法が不評だったというのは、ibus1.5への移行時の混乱だと受けとって以下の文を書いています。

ibus1.4の仕様はネット検索からの推測です。実際に使用したことはありません。

- 初期入力状態は英数入力
- 全角半角キーで入力状態を切りかえる

この方法が主流ですから、この方法から外れていると非難の対象になったのではないかと想像しています。

### 旧ibus
ibus1.4以前はibus自体をオンオフ切りかえしていた。このショートカットキーに全角半角キーが含まれていた。
変換エンジン側の全角半角キーへの割りあてはibus側に吸収されて、変換エンジンには届いていなかった。
設定を変更していなければ、ibusの初期状態はオフである。
とすると変換エンジンが英数入力モードで起動すると、日本語入力モードにするためにibusの起動、変換エンジンのモード変更という余計な手順を踏むことになる。
このときMozcは日本語入力モードで起動していた。
初期入力モードの設定ができる変換エンジンを使っている人の中には設定でibusの初期状態をオンにして、変換エンジン側で入力モードの切りかえをしている人もいた。

### 新ibus
ibus1.5ではibusは起動しっぱなしである。
レイアウト変更キーに全角半角キーが含まれていない。
よってそのままでは主流の操作方法から外れるので混乱があったのではないかと思います。

ここで変更への対応方法として2通りあります。
- ibusに直接入力用のレイアウトと変換エンジンを登録し、レイアウト変更キーに全角半角キーを追加する。
- ibusに変換エンジンのみを登録し、変換エンジン側で入力モードの切りかえをする。

前者の方法だと変換エンジンが英数入力モードで起動すると、日本語入力モードにするためにibusのレイアウト変更、変換エンジンのモード変更という余計な手順を踏むことになる。
後者の方法だと変換エンジンが日本語入力モードで起動すると、初期入力状態が日本語入力になる。
Mozcはこの問題に対応するために英数入力モードで起動するよう仕様を変更した。

よって前者の方法をとった人から非難の対象になったのではないかと思います。

また後者の方法だと、外部プログラムから入力モードを操作するためには、変換エンジン側でなにかしら方法が用意されないといけません。
これもまた非難の対象になったのではないかと思います。

**Comment by h-youhei** [comment]
提案された方法は使う側としても簡単そうで良いと思います。
vimのリモートプラグイン経由でpythonライブラリをインポートしてごにょごにょってのを想像していたので驚いています。

ibus共通の方法が使えるというのがエンジンごと切りかえる方法での利点です。

僕個人はどちらの方法でも問題ありません。

**Comment by h-youhei** [comment]
複数言語を入力しようとするとエンジンごと切りかえる方法では問題があることがわかりました。
例えば、日本語と中国語と英語を入力するとします。
日本語と英語間、中国語と英語間での切りかえは頻度が多くなり、日本語、中国語間での切りかえは頻度が少なくなります。
英語、日本語、中国語、英語…以下繰りかえしの順でエンジンが切りかわるとして、日本語から英語にしたいとき、英語から中国語にしたいときに余計な手順が増えます。

**Comment by ShikiOkasaka** [comment]
調査とコメント、ありがとうございました。

ef22169d1208ada13e158a47bb5e4acf691f0c65 で、GSettings をつかって入力モードを変更できるようにしました。
英語キーボードで Caps Lock が[A/あ]になる点はそのままですが、GSettings で変更した場合は、次回 Caps Lock キーが操作されるまでは、GSettings 経由の設定が優先されるようにしています。

**Comment by ShikiOkasaka** [comment]
「ibusのエンジンごと切りかえる方法が不評」とかいたのは、ibus 1.5.11 で icon-prop-key が導入されて、トップバーに入力モードを表示できる形にもどった(?)点を想定していました。
https://github.com/ibus/ibus/commit/23c45b970b195008a54884a1a9d810e7f8b22c5c

印象としては、日本語のなかで、漢字とひらがなをいれるモード、カタカナをいれるモード、アルファベットをいれるモードの３つがある、ということであって、言語をきりかえているわけではない、という感覚なのではないかな、と。

**Comment by h-youhei** [comment]
ありがとうございます。
うまく動いています。
https://github.com/h-youhei/vim-ibus-replace-with-kanji

**Comment by ShikiOkasaka** [comment]
確認ありがとうございます。
このissueはひとまずクローズしておきます。
