### ISSUE TITLE
接頭辞、接尾辞の優先順位

### ISSUE THREAD

**Issue by h-youhei** [esrille/ibus-replace-with-kanji#37]
skkに接頭辞、接尾辞変換があるために、そういった変換を持たない変換エンジンにとっては、skk辞書での接頭辞、接尾辞の優先順位が低くなりすぎていると思います。

そのため、はじめて変換する際に、何度も変換キー押さなくてはならない語がけっこうあるんではないかと思います。

一度変換してしまえば、学習機能により問題なくなるので大きな問題ではないと思いますが、いずれ対策をとったほうがいいかと。

skkで使われている接頭辞、接尾辞一覧があればそれにある漢字を一番上に持ってきてしまうのが応急処置としてはいいんではないかと思います。

気づいた文字をあげていきます(随時更新)
化 超 値

**Comment by ShikiOkasaka** [comment]
関連して、いまの辞書で数助詞はまえのほうにならんでいる、というのには気づきましたか?

**Comment by h-youhei** [comment]
気づいていませんでした。

**Comment by ShikiOkasaka** [comment]
まえのほうにあれば、そんなに気にならない、ということかもしれませんね。検討してみます。

ちなみに今は、助数詞、そのあとに、ならう学年順で単漢字はならんでいます。

**Comment by h-youhei** [comment]
習う学年順でしたか。
とんでもない勘違い失礼しました。

**Comment by ShikiOkasaka** [comment]
学年順というのは、学年別辞書のときにそうしたものなので、
助数詞→接頭辞→接尾辞→学年順、
というのも、あってよいとおもっています。

ただ、接頭辞、接尾辞は、梅棹さんが「大規模」に「第規模」のようなありえない語を提示してくる初期のワープロを（辞書登録何万語というみせかけの）「詐欺」といわれていた、というようなこともあって、基本的には辞書登録するのがよいようにはかんがえています。

**Comment by h-youhei** [comment]
基本的には辞書登録するのに賛成します。

skkのML辞書から接頭辞と接尾辞を抜きだして。それをもとにL辞書から複合語を抜きだしてみるといいと思いました。
とりあえずML辞書から接頭辞と接尾辞を抜きだす[スクリプト](https://gist.github.com/h-youhei/0655902d559689e18dcc1c2688a3b713)を書いてみました。
[こちらが抜きだしたもの](https://gist.github.com/h-youhei/00b8295eee1f34b9b41e08b3bc58cabd)です。

接頭辞から
- 水酸化
- 比較的

接尾辞から
- 営業所
- 親方
- 組み
- 支店
- 辞典
- 先生
- 全体
- 大学
- 付き
- 当時
- 同士
- 行き
- 予定

を除けばいいと思います。
ほかに除いたほうがいいものなど意見があれば教えてください。

複合語を抜きだすのは/漢字1/漢字2/を分解して、接尾辞は`/.+漢字/`、接頭辞は`/漢字.+/`の正規表現にかければいいと思います。

**Comment by ShikiOkasaka** [comment]
接頭辞で、数字につながる「第, 全, 約」などは、単漢字のリストでもまえのほうにあったほうがよさそうですね。

辞書については、L辞書からrestrained.dicをつくることもできます。現行のML辞書ベースのものでは不足というかたは、L辞書ベースのものをつかっていただいてもよいので、ML辞書にL辞書の単語を追加するというのは、よいのかどうか、といったことはあるようにおもいます。

ユーザー辞書の拡張用の簡単なUIがあったほうがよいのか、といったあたりもかんがえてみてよいのかもしれません。個人的には、my.dicを直接編集して、

    $ ibus restart

という手順でいまのところすんでしまっていますが、どうでしょうか?

**Comment by ShikiOkasaka** [comment]
辞書登録で対応する方向で、ということで、このIssue自体はクローズします。
