### ISSUE TITLE
キーカスタマイズ

### ISSUE THREAD

**Issue by h-youhei** [esrille/ibus-replace-with-kanji#41]
変換キーと無変換キー以外の機能キー（区切りキー、状態切りかえキーなど）もユーザーがわで割りあてれると嬉しいです。

僕が別のキーに割りあてたい機能は以下のとおりです。
- 送りがなの位置指定
- 英数/かなモードの切りかえ（スイッチ式）
- カタカナ置換

また、現状のコードだとShiftなど修飾キーを伴う割りあてが難しいので、それを想定したコードに書きかえていくといいと思います。

そのために
- キー設定の書きかたを定める(例えば「S-」が頭に付いていたらShift）
- キー設定を持つ変数のデータ構造を、keymodとkeysymを持つTupleかClassに変更
- キー設定をパースする関数を書く
- その関数経由でキー設定を持つ変数に代入
- process_key_event()を新しいデータ構造に対応させる

Readmeにキーカスタマイズの項目を作って、[ibusのkeysym一覧](https://ibus.github.io/docs/ibus-1.5/ibus-IBusKeysyms.html)にリンクを貼っておくと親切だと思います。
関係する部分を抜きだして、文書化しておくとよりよいです。

**Comment by ShikiOkasaka** [comment]
機能としてはもちろんあってよいのですが、いまのところのウェイトは、標準のキーアサインをつめていくことかとおもっています。

この機能をこのキーに(基本的には指１本で操作できるもの)、といったことがありましたら、あわせておしらせください。

**Comment by h-youhei** [comment]
[ibusのkeysymをまとめてみました](https://gist.github.com/h-youhei/06e2e0a3b9fabbf93dbfd381edd5c3ca)

replace-with-kanjiを使う前はシステム側でqwerty(us)配列、
Ergodoxでキー配列の変更をし、変換・無変換・かな/カナキー・Alt-`（全角・半角のかわり）を追加して使ってました。

replace-with-kanjiでは、 \ をShift側のあまった文字に割りあてて、Ergodoxでそのキー、RShift(カタカナ)、F13(Space)を追加、
F13を押すとPCが固まるので使わないキーに変えてXmodmapでF13に割りあてて使っていました。原因はわかりませんがXmodmapが不安定でなにかの拍子に効かなくなるのが困りました。

変換を親指で1番押しやすい両手のキー(Space)、Enterを2番目に押しやすい左手のキー、送り位置を2番目に押しやすい右手のキー、モード切りかえに3番目に押しやすい左手のキーに持ってくると使いやすかったです。
空白とカタカナはいい場所がなかったので左右最上段に置いて中指で押してました。とくに問題ありませんでした。
また、Shiftキーは親指で1番押しやすいキーとのデュアルキー(SandS)にしています。

Tabで読みを短縮するのは賛成です。

頻度を考えると、変換はjisキーボードでもSpaceキーを使うほうがいいと思います。英語と日本語でスペースを別のキーで打ちわけることを嫌っての選択ですか？

送り位置指定は。用言を漢字にするひとには、変換キーや無変換キーに当てたい頻度です。バックスラッシュは無Shift文字すべてにかなを割りあてた配列で困ります。僕が作っている配列のほかにusキーボード用jisかな入力もそうです。

頻度を考えると空白には全角/半角キー、
英数/かな切りかえには変換キーと無変換キーの送り位置指定に当てなかったほうを割りあてるといいと思います。

カタカナ置換は押しにくくてもいいけども、連打はしやすいぼうがいいです。スペースキーが短いキーボードのカタカナキー（Mの右下）がちょうどいいです。

Enterキーで変換候補の確定をしたいときより改行したいときのほうが圧倒的に多いので、確定が邪魔だと感じていますが、確定がないと困る場合もあります。
skkを使っていたときは、なぜ確定がなくても困らなかったのか考えてみました。数字キーでの確定でした。
数字キーでの確定は4段かな入力で邪魔になります。FunctionキーやCtrlキー+数字キーではどうでしょうか。

Capslockは使うひとは結構使うキーです。インジケータと連動していなければ日本語と英語で別の機能をさせることができていいんですけど。
英文入力やプログラミングにCapslockを使えないのは困るので今はMozcを使っています。

Ctrlキーは手の側面だと押しやすいことを考慮にいれるといいかもしれません。ただ連打はしにくいです。

usキーボードだと左右Ctrl・左右Shift・右Alt・右Super(Win)しかあいてません。
僕だったらこうします。
- 左Ctrl 送り位置
- 右Ctrl 英数/かな
- 右Alt カタカナ置換
- 右Super 空白
usキーボードの右Shiftは「ろ」の位置まで伸びているようで、それならShiftの左右の打ちわけもしやすく、打ちわけるならShiftはわりと打つので誤爆が気になると思い避けました。
いや、Shiftをわりと使うのは英語なので日本語入力側でのみ使う（「英数/かな」はあてはまらず「送り位置」や「カタカナ置換」はあてはまる）機能を割りあてるといいかもしれません。

特殊な事例ばかりでごめんなさい。

**Comment by ShikiOkasaka** [comment]
すこし説明不足でした。「標準のキーアサインを」とかいたのは、こちらのページ、

https://esrille.github.io/ibus-replace-with-kanji/layouts.html

にのせている、標準的な英語キーボードでの、

* New Stickney配列(あるいは同様な３段１０列のかな配列) と、
* ローマ字配列、

の場合です。これ以上に議論をひろげる必要性はあまりなさそうなので。（現行のJISキーボードは、みなさん問題点を指摘されていますが、特殊キーはそのまま刻印どおりにつかう、というイメージでいます。）

CAPS(英数)キーを[A/あ]相当にされているひとは、Windowsではおおい印象ですが、Mac風の操作をこのまれるひともおおいですね。最後は設定パネルのスイッチで、というのはあるのですが、こどもにおしえるときにわかりやすい方法を、といったことをイメージしてくださるとよいかとおもいます。

**Comment by ShikiOkasaka** [comment]
いまの時点では、標準のキーアサインの確定をいそぐ、ということで、このIssueはクローズします。
