### ISSUE TITLE
よみの短縮の学習

### ISSUE THREAD

**Issue by ShikiOkasaka** [esrille/ibus-replace-with-kanji#48]
よみの短縮操作は、ibus-replace-with-kanjiでストレスを感じる操作になりやすい。そこで、

```
しのじ〔変換〕
し野地〔タブ〕
しの字
```
のように、「しのじ」を「しの字」と置換したときに、「のじ」というよみに対して「の字」を学習するようにしてみる。

この上の文でも「と置換」ははじめは「土地勘」と置換されるが、この機能によって次回以降はまず「と置換」と置換されるようになる。

まずは、このような単純な辞書学習機能でどの程度よみの短縮の負担をへらせるかを確認する。

**Comment by ShikiOkasaka** [comment]
c2653e4361aa338bc0f4c390090dc8598f7b51b5 で実装しています。

**Comment by ShikiOkasaka** [comment]
実行中の様子:

![shrink](https://user-images.githubusercontent.com/3130013/31760987-6f03dece-b4f1-11e7-8529-7fa45e6c12ed.png)

**Comment by MadeInWarioFan** [comment]
>この上の文でも「と置換」ははじめは「土地勘」と置換されるが、この機能によって次回以降はまず「と置換」と置換されるようになる。
先生の方法も納得できます．しかし，変換中にTabを誤って押しすぎたときに読みを延長するキーアサインが必要なくなるわけではありません．
「ここで履物をぬいでください．」と打ちたいときに，[ここで<履物>]のあとに誤ってTabを押して[ここでは<着物>]とするミスがあります．そのときに，読み延長の操作をして[ここで<履物>]に戻す操作が必要になります．

読み延長のキーアサインの一案:
左Alt+Tab （左ShiftとTabは同時に押せず，右ShiftはUSキーボードのカタカナ置換キーですので）

**Comment by MadeInWarioFan** [comment]
>この上の文でも「と置換」ははじめは「土地勘」と置換されるが、この機能によって次回以降はまず「と置換」と置換されるようになる。

 先生の方法も納得できます．しかし，変換中にTabを誤って押しすぎたときに読みを延長するキーアサインが必要なくなるわけではありません．
 「ここで履物をぬいでください．」と打ちたいときに，[ここで<履物>]のあとに誤ってTabを押して[ここでは<着物>]とするミスがあります．そのときに，読み延長の操作をして[ここで<履物>]に戻す操作が必要になります．

読み延長のキーアサインの一案:
左Alt+Tab （左ShiftとTabは同時に押せず，右ShiftはUSキーボードのカタカナ置換キーですので）

**Comment by ShikiOkasaka** [comment]
実際の学習結果の一例:

````
てき /て気/的/滴/笛/適/敵/摘/テキ/
はいち /は位置/配置/ハイチ/
はず /は図/ハズ/
いほん /い本/異本/
うかん /う感/有漢/
うてん /う点/雨天/
がいろん /がい論/概論/
きいち /きい値/喜一/
さんりゅう /さん流/三流/
じじゅん /じ順/耳順/
たいじょう /た以上/退場/帯状/
たさい /た際/多彩/多才/
とちかん /と置換/土地勘/
におう /に応/仁王/
のかた /の型/野方/
のかみ /の紙/野上/
のじ /の字/野地/野路/
のてん /の点/野天/
のなか /の中/野中/
はいみ /は意味/俳味/
はやく /は役/は約/端役/破約/
ようちゅうい /よう注意/要注意/
りやく /り役/利益/
````

**Comment by ShikiOkasaka** [comment]
v0.5.0でリリースしました。
